{
  "type": "record",
  "name": "OrderCreatedEvent",
  "namespace": "com.aryan.kafka.avro",
  "fields": [
    {
      "name": "eventId",
      "type": "string"
    },
    {
      "name": "orderId",
      "type": "long"
    },
    {
      "name": "productId",
      "type": "long"
    },
    {
      "name": "quantity",
      "type": "int"
    },
    {
      "name": "amount",
      "type": {
        "type": "bytes",
        "logicalType": "decimal",
        "precision": 19,
        "scale": 2
      }
    },
    {
      "name": "status",
      "type": "string"
    },
    {
      "name": "occurredAt",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "source",
      "type": "string",
      "default": "UNKNOWN"
    }
  ]
}